### ISSUE TITLE
by_family.py doesn't fail if conditions not met

### ISSUE THREAD

**Issue by christianfiles** [AWGL/DragenWGS#18]
When running some gel trio samples through this pipeline it was not immediately obvious why the script was failing.

After some digging it was because the depth was too low. I traced this back to: [https://github.com/AWGL/DragenWGS/blob/master/commands/by_family.py](url) 
The min depth is assigned a variable of 5. However, if the min depth of the sample is below 5 an empty dictionary is still created and this then fails the pipeline downstream of this script.

Maybe be worth adding a try except block here to capture these? As it seems like we are running more and more trios through this pipeline that don't get captured with min depth thresholds beforehand.

**Comment by josephhalstead** [comment]
Why would GeL samples be using this pipeline?
