### ISSUE TITLE
Extracting fields from normal in vcf

### ISSUE THREAD

**Issue by MaryGoAround** [AWGL/DragenWGS#27]
Hi 
I am working on `UK biobank WGS data`. From `DRAGEN` vcf files, I realised in each vcf file, we do not have two columns for germline and somatic variants rather per sample we have only one sample column in vcf file like below
 
```
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  **2072184**
chr1    10109   .   AACCCT  A   21.51   PASS    AC=2;AF=1.000;AN=2;DP=10;FS=8.451;MQ=13.01;MQRankSum=0.000;QD=2.15;ReadPosRankSum=-1.300;SOR=3.236;FractionInformativeReads=0.700;R2_5P_bias=0.000  GT:AD:AF:DP:F1R2:F2R1:GQ:PL:GP:PRI:SB:MB    ./.:3,4:0.571:7:1,1:2,3:6:30,8,0:2.1511e+01,5.8560e+00,1.3473e+00:0.00,7.00,10.01:1,2,4,0:3,0,1,3
 
```
 
Having such a vcf files, is still possible to extract some fields but only from normal part (germline or blood) ? Because I only need variants from matched normal part of a vcf file comes from a patient.
 
Thanks for any help
 
This is the fields I want to extract only for germline not somatic.
 
`--format '[%SAMPLE]\t%CHROM\t%POS\t%ID\t%cosmic\t%REF\t%ALT\t%QUAL\t%FILTER\t[%DP]\n'`

**Comment by josephhalstead** [comment]
Hi Mary - this is not the official dragen repo. Just a script for using the DRAGEN we have here in Wales. Not sure we can be of much help!
