### ISSUE TITLE
Fails to upload to AutoQC database when NTC has no reads

### ISSUE THREAD

**Issue by erikwaskiewicz** [AWGL/DragenWGS#7]
`*.mapping_metrics.csv` isn't produced if there are no reads in the BAM, and this file is required by AutoQC to mark the sample as valid, needs some handling in case this happens again

Happened twice now - AutoQC run_analysis 1316 and 4863

**Temporary solution:**
- Check that BAM file has no reads (e.g. `samtools view <bam_file>`). 
- Make an empty file called `<run_id>_<sample_id>.mapping_metrics.csv`
- AutoQC should now update after the cron job runs

**Comment by SophieS9** [comment]
Same issue has happened for AutoQC run analysis 4997 and 4998.

**Comment by erikwaskiewicz** [comment]
And 5036

**Comment by josephhalstead** [comment]
closed by pull request #16
